project_id = "otwhubuqkjjosejfiwos"

[functions.nuvemshop]
verify_jwt = false

[functions.nuvemshop-oauth]
verify_jwt = false

[functions.send-return-notification]
verify_jwt = false

[functions.melhor-envio]
verify_jwt = false
